/** The plugins as the landing page lists them: the package's short name and one line. */
export const PLUGINS: Array<{ name: string; title: string; line: string }> = [
  { name: 'api', title: 'Plugin contract', line: 'The types, decorators and fake host every plugin is written and tested against.' },
  { name: 'layout', title: 'Layout', line: 'Panels in columns, their widths and order — the frame everything else sits in.' },
  { name: 'editor', title: 'Editor', line: 'CodeMirror 6: git markers beside the lines, the diff over the text, and the empty pasture.' },
  { name: 'code', title: 'Code display', line: 'The one way code is shown: languages, highlighting and the editor defaults.' },
  { name: 'doc', title: 'Documents', line: 'Unsaved edits, files changed on disk, and the strip that says so.' },
  { name: 'tree', title: 'Project tree', line: 'The file tree: type to find, drag to move, and copy, paste, rename.' },
  { name: 'search', title: 'Search everywhere', line: 'Shift+Shift over files, symbols, scripts, terminals and settings, with typed tags.' },
  { name: 'symbols', title: 'Symbols', line: 'Every function, class and interface in the project, parsed in the background.' },
  { name: 'find', title: 'Find', line: 'Find and replace in a file and across the project, including unsaved edits.' },
  { name: 'completion', title: 'Completion', line: 'Completion with its own ranking that learns what you pick.' },
  { name: 'lsp', title: 'Language servers', line: 'LSP: diagnostics, hover, go to definition, references; TypeScript out of the box.' },
  { name: 'problems', title: 'Problems', line: 'Everything the language servers found, across the project, in one panel.' },
  { name: 'terminal', title: 'Terminal', line: 'Real terminals under xterm.js that live in the daemon and survive a reload.' },
  { name: 'npm-scripts', title: 'npm scripts', line: 'Every script of every package.json, run in its own terminal.' },
  { name: 'rerun', title: 'Rerun', line: 'Run the last script again. Twenty lines, and the example in the docs.' },
  { name: 'debug', title: 'Debugger', line: 'DAP through vscode-js-debug: breakpoints, logpoints, stepping, a browser under the debugger.' },
  { name: 'git', title: 'Git', line: 'Branches, fetch, pull and push with a preview of what goes out.' },
  { name: 'changes', title: 'Changes', line: 'Changelists, commits, a shelf of patches, and the diff over the editor.' },
  { name: 'merge', title: 'Merge', line: 'A three-way merge screen for conflicts, from git or from disk.' },
  { name: 'projects', title: 'Projects', line: 'Open a project by path with completion, and switch between recent ones.' },
  { name: 'visits', title: 'Caret history', line: 'Back and forward through where the caret has been, across files.' },
  { name: 'settings', title: 'Settings', line: 'A settings window over the same JSON file you edit by hand.' },
  { name: 'keymap', title: 'Keymap', line: 'Keys as data: one dispatcher, a keymap editor, and the keys the browser keeps.' },
  { name: 'keys', title: 'Keys window', line: 'Press a key and see what it does, and why a taken one is taken.' },
  { name: 'toolbar', title: 'Toolbar', line: 'The strip of buttons on top, ordered by settings.' },
  { name: 'notifications', title: 'Notifications', line: 'What the IDE has to say, as lines rather than modal dialogs.' },
  { name: 'daemon', title: 'Daemon memory', line: 'How much the daemon and everything it started hold, on the toolbar.' },
  { name: 'theme', title: 'Theme', line: 'Darcula, as a palette of CSS variables.' },
  { name: 'ui', title: 'Widgets', line: 'Popups, menus, icons and chips shared by every other plugin.' },
  { name: 'image', title: 'Image viewer', line: 'Images and SVG shown as themselves.' },
  { name: 'markdown', title: 'Markdown', line: 'Markdown rendered, side by side with its source.' },
  { name: 'sheep', title: 'Sheep', line: 'Pixel sheep grazing in an empty editor. Switch it off, if you must.' },
];
