export const RUSSIAN_DEBT: readonly string[] = [
  'desktop/src/daemon.ts',
  'plugins/completion/src/server.ts',
  'plugins/git/src/cli.ts',
  'plugins/git/src/index-git.ts',
  'plugins/git/src/server.ts',
  'plugins/lsp/src/lsp-server.ts',
  'plugins/lsp/src/server.ts',
  'plugins/lsp/src/toolchain.ts',
  'plugins/merge/src/server.ts',
  'plugins/merge/src/sessions.ts',
  'plugins/search/src/server.ts',
  'plugins/terminal/src/server.ts',
  'plugins/tree/src/server.ts',
];
