import type { Keymap } from './types.js';

export const FACTORY_KEYMAP: Keymap = {
  "version": 2,
  "bindings": [

    { "command": "search.everywhere", "key": "double:shift" },
    { "command": "scripts.open", "key": "double:meta", "where": ["browser:mac", "electron:mac"] },
    { "command": "scripts.open", "key": "meta+shift+s", "where": ["browser:mac", "electron:mac"] },
    { "command": "scripts.open", "key": "control+shift+s", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "scripts.rerun", "key": "meta+shift+enter", "where": ["browser:mac", "electron:mac"] },
    { "command": "scripts.rerun", "key": "control+shift+enter", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "projects.show", "key": "double:control" },
    { "command": "git.branches", "key": "double:alt", "where": ["browser:mac", "electron:mac"] },
    { "command": "popup.close", "key": "escape" },
    { "command": "prompt.confirm", "key": "enter", "when": "prompt" },
    { "command": "search.next", "key": "arrowdown", "when": "search" },
    { "command": "search.prev", "key": "arrowup", "when": "search" },
    { "command": "search.accept", "key": "enter", "when": "search" },
    { "command": "search.close", "key": "escape", "when": "search" },
    { "command": "pick.next", "key": "arrowdown", "when": "pick" },
    { "command": "pick.prev", "key": "arrowup", "when": "pick" },
    { "command": "pick.accept", "key": "enter", "when": "pick" },
    { "command": "pick.expand", "key": "arrowright", "when": "pick" },
    { "command": "merge.next", "key": "arrowdown", "when": "merge" },
    { "command": "merge.prev", "key": "arrowup", "when": "merge" },
    { "command": "merge.takeLeft", "key": "arrowleft", "when": "merge" },
    { "command": "merge.takeRight", "key": "arrowright", "when": "merge" },
    { "command": "merge.skipLeft", "key": "shift+arrowleft", "when": "merge" },
    { "command": "merge.skipRight", "key": "shift+arrowright", "when": "merge" },
    { "command": "merge.nextFile", "key": "tab", "when": "merge" },
    { "command": "merge.prevFile", "key": "shift+tab", "when": "merge" },
    { "command": "merge.confirm", "key": "enter", "when": "merge" },
    { "command": "menu.next", "key": "arrowdown", "when": "menu" },
    { "command": "menu.prev", "key": "arrowup", "when": "menu" },
    { "command": "menu.accept", "key": "enter", "when": "menu" },
    { "command": "projects.next", "key": "arrowdown", "when": "projects" },
    { "command": "projects.prev", "key": "arrowup", "when": "projects" },
    { "command": "projects.complete", "key": "tab", "when": "projects" },
    { "command": "projects.accept", "key": "enter", "when": "projects" },
    { "command": "projects.close", "key": "escape", "when": "projects" },
    { "command": "projects.suggest", "key": "meta+shift+space", "when": "projects", "where": ["browser:mac", "electron:mac"] },
    { "command": "projects.suggest", "key": "control+shift+space", "when": "projects", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },

    { "command": "find.open", "key": "meta+f", "where": ["browser:mac", "electron:mac"] },
    { "command": "find.open", "key": "control+f", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "find.replace", "key": "meta+r", "where": ["browser:mac", "electron:mac"] },
    { "command": "find.replace", "key": "control+h", "where": ["browser:win", "browser:linux"] },
    { "command": "find.replace", "key": "control+r", "where": ["electron:win", "electron:linux"] },
    { "command": "find.next", "key": "meta+g", "where": ["browser:mac", "electron:mac"] },
    { "command": "find.next", "key": "f3" },
    { "command": "find.prev", "key": "shift+f3" },
    { "command": "find.next", "key": "enter", "when": "find" },
    { "command": "find.prev", "key": "shift+enter", "when": "find" },
    { "command": "find.close", "key": "escape", "when": "find" },
    { "command": "find.close", "key": "escape", "when": "editor" },
    { "command": "find.close", "key": "escape", "when": "find-replace" },
    { "command": "find.replaceOne", "key": "enter", "when": "find-replace" },
    { "command": "find.newline", "key": "meta+enter", "when": "find", "where": ["browser:mac", "electron:mac"] },
    { "command": "find.newline", "key": "control+enter", "when": "find", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "find.toggleCase", "key": "meta+alt+c", "when": "find", "where": ["browser:mac", "electron:mac"] },
    { "command": "find.toggleWords", "key": "meta+alt+w", "when": "find", "where": ["browser:mac", "electron:mac"] },
    { "command": "find.toggleRegex", "key": "meta+alt+x", "when": "find", "where": ["browser:mac", "electron:mac"] },
    { "command": "find.toggleCase", "key": "alt+c", "when": "find", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "find.toggleWords", "key": "alt+w", "when": "find", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "find.toggleRegex", "key": "alt+x", "when": "find", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "field.native", "key": "enter", "when": "find-multiline" },
    { "command": "field.native", "key": "shift+enter", "when": "find-multiline" },
    { "command": "find.close", "key": "escape", "when": "find-multiline" },
    { "command": "find.newline", "key": "meta+enter", "when": "find-multiline", "where": ["browser:mac", "electron:mac"] },
    { "command": "find.newline", "key": "control+enter", "when": "find-multiline", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "find.toggleCase", "key": "meta+alt+c", "when": "find-multiline", "where": ["browser:mac", "electron:mac"] },
    { "command": "find.toggleWords", "key": "meta+alt+w", "when": "find-multiline", "where": ["browser:mac", "electron:mac"] },
    { "command": "find.toggleRegex", "key": "meta+alt+x", "when": "find-multiline", "where": ["browser:mac", "electron:mac"] },
    { "command": "find.toggleCase", "key": "alt+c", "when": "find-multiline", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "find.toggleWords", "key": "alt+w", "when": "find-multiline", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "find.toggleRegex", "key": "alt+x", "when": "find-multiline", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "find.replaceAll", "key": "meta+alt+enter", "when": "find-replace", "where": ["browser:mac", "electron:mac"] },
    { "command": "find.replaceAll", "key": "control+alt+enter", "when": "find-replace", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "find.files", "key": "meta+shift+f", "where": ["browser:mac", "electron:mac"] },
    { "command": "find.files", "key": "control+shift+f", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "find.filesReplace", "key": "meta+shift+r", "where": ["browser:mac", "electron:mac"] },
    { "command": "find.filesReplace", "key": "control+shift+h", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "findFiles.next", "key": "arrowdown", "when": "find-files" },
    { "command": "findFiles.prev", "key": "arrowup", "when": "find-files" },
    { "command": "findFiles.accept", "key": "enter", "when": "find-files" },
    { "command": "findFiles.close", "key": "escape", "when": "find-files" },
    { "command": "findFiles.nextField", "key": "tab", "when": "find-files" },
    { "command": "findFiles.toggleCase", "key": "meta+alt+c", "when": "find-files", "where": ["browser:mac", "electron:mac"] },
    { "command": "findFiles.toggleWords", "key": "meta+alt+w", "when": "find-files", "where": ["browser:mac", "electron:mac"] },
    { "command": "findFiles.toggleRegex", "key": "meta+alt+x", "when": "find-files", "where": ["browser:mac", "electron:mac"] },
    { "command": "findFiles.toggleCase", "key": "alt+c", "when": "find-files", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "findFiles.toggleWords", "key": "alt+w", "when": "find-files", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "findFiles.toggleRegex", "key": "alt+x", "when": "find-files", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "findFiles.replaceAll", "key": "meta+alt+enter", "when": "find-files", "where": ["browser:mac", "electron:mac"] },
    { "command": "findFiles.replaceAll", "key": "control+alt+enter", "when": "find-files", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "findFiles.replaceFile", "key": "meta+enter", "when": "find-files", "where": ["browser:mac", "electron:mac"] },
    { "command": "findFiles.replaceFile", "key": "control+enter", "when": "find-files", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "findFiles.addMask", "key": "enter", "when": "find-files-mask" },
    { "command": "findFiles.close", "key": "escape", "when": "find-files-mask" },
    { "command": "findFiles.nextField", "key": "tab", "when": "find-files-mask" },
    { "command": "findFiles.next", "key": "arrowdown", "when": "find-files-mask" },
    { "command": "findFiles.prev", "key": "arrowup", "when": "find-files-mask" },
    { "command": "field.native", "key": "meta+z", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "meta+shift+z", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "meta+a", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "meta+arrowleft", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "meta+arrowright", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "meta+arrowup", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "meta+arrowdown", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "meta+shift+arrowleft", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "meta+shift+arrowright", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "meta+shift+arrowup", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "meta+shift+arrowdown", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "alt+arrowleft", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "alt+arrowright", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "alt+shift+arrowleft", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "alt+shift+arrowright", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "alt+backspace", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "alt+delete", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "meta+backspace", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "meta+delete", "when": "editable", "where": ["browser:mac", "electron:mac"] },
    { "command": "field.native", "key": "control+z", "when": "editable", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "field.native", "key": "control+y", "when": "editable", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "field.native", "key": "control+shift+z", "when": "editable", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "field.native", "key": "control+a", "when": "editable", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "field.native", "key": "control+arrowleft", "when": "editable", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "field.native", "key": "control+arrowright", "when": "editable", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "field.native", "key": "control+shift+arrowleft", "when": "editable", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "field.native", "key": "control+shift+arrowright", "when": "editable", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "field.native", "key": "control+backspace", "when": "editable", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "field.native", "key": "control+delete", "when": "editable", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "key.reserved", "key": "tab" },
    { "command": "key.reserved", "key": "shift+tab" },

    { "command": "file.save", "key": "meta+s", "where": ["browser:mac", "electron:mac"] },
    { "command": "file.save", "key": "control+s", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "file.reload", "key": "alt+shift+r", "where": ["browser:mac"] },
    { "command": "file.reload", "key": "control+alt+r", "where": ["browser:win", "browser:linux"] },
    { "command": "file.reload", "key": "control+shift+r", "where": ["electron:win", "electron:linux"] },
    { "command": "file.reload", "key": "alt+shift+r", "where": ["electron:mac"] },

    { "command": "panel.tree", "key": "meta+1", "where": ["browser:mac", "electron:mac"] },
    { "command": "panel.tree", "key": "control+alt+1", "where": ["browser:win", "browser:linux"] },
    { "command": "panel.tree", "key": "control+1", "where": ["electron:win", "electron:linux"] },
    { "command": "search.everywhere", "key": "meta+2", "where": ["browser:mac", "electron:mac"] },
    { "command": "search.everywhere", "key": "control+alt+2", "where": ["browser:win", "browser:linux"] },
    { "command": "search.everywhere", "key": "control+2", "where": ["electron:win", "electron:linux"] },
    { "command": "git.branches", "key": "meta+3", "where": ["browser:mac", "electron:mac"] },
    { "command": "git.branches", "key": "control+alt+3", "where": ["browser:win", "browser:linux"] },
    { "command": "git.branches", "key": "control+3", "where": ["electron:win", "electron:linux"] },
    { "command": "git.push", "key": "meta+4", "where": ["browser:mac", "electron:mac"] },
    { "command": "git.push", "key": "control+alt+4", "where": ["browser:win", "browser:linux"] },
    { "command": "git.push", "key": "control+4", "where": ["electron:win", "electron:linux"] },
    { "command": "panel.problems", "key": "meta+5", "where": ["browser:mac", "electron:mac"] },
    { "command": "panel.problems", "key": "control+alt+5", "where": ["browser:win", "browser:linux"] },
    { "command": "panel.problems", "key": "control+5", "where": ["electron:win", "electron:linux"] },
    { "command": "terminal.create", "key": "meta+6", "where": ["browser:mac", "electron:mac"] },
    { "command": "terminal.create", "key": "control+alt+6", "where": ["browser:win", "browser:linux"] },
    { "command": "terminal.create", "key": "control+6", "where": ["electron:win", "electron:linux"] },
    { "command": "projects.show", "key": "meta+7", "where": ["browser:mac", "electron:mac"] },
    { "command": "projects.show", "key": "control+alt+7", "where": ["browser:win", "browser:linux"] },
    { "command": "projects.show", "key": "control+7", "where": ["electron:win", "electron:linux"] },
    { "command": "panel.editor", "key": "meta+8", "where": ["browser:mac", "electron:mac"] },
    { "command": "panel.editor", "key": "control+alt+8", "where": ["browser:win", "browser:linux"] },
    { "command": "panel.editor", "key": "control+8", "where": ["electron:win", "electron:linux"] },
    { "command": "keys.show", "key": "meta+9", "where": ["browser:mac", "electron:mac"] },
    { "command": "keys.show", "key": "control+alt+9", "where": ["browser:win", "browser:linux"] },
    { "command": "keys.show", "key": "control+9", "where": ["electron:win", "electron:linux"] },
    { "command": "settings.show", "key": "meta+comma", "where": ["browser:mac", "electron:mac"] },
    { "command": "settings.show", "key": "control+comma", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },

    { "command": "debug.stepInto", "key": "f7" },
    { "command": "debug.stepOver", "key": "f8" },
    { "command": "debug.stepOut", "key": "shift+f8" },
    { "command": "debug.continue", "key": "f9" },
    { "command": "debug.file", "key": "shift+f9" },
    { "command": "debug.toggleBreakpoint", "key": "meta+f8", "where": ["browser:mac", "electron:mac"] },
    { "command": "debug.toggleBreakpoint", "key": "control+f8", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "debug.stop", "key": "meta+f2", "where": ["browser:mac", "electron:mac"] },
    { "command": "debug.stop", "key": "control+f2", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "panel.debug", "key": "meta+shift+d", "where": ["browser:mac", "electron:mac"] },
    { "command": "panel.debug", "key": "control+shift+d", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },

    { "command": "git.branches", "key": "meta+backquote", "where": ["electron:mac"] },
    { "command": "git.branches", "key": "control+backquote", "where": ["browser:mac", "electron:mac"] },
    { "command": "git.branches", "key": "control+backquote", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "git.push", "key": "meta+shift+k", "where": ["browser:mac", "electron:mac"] },
    { "command": "git.push", "key": "control+shift+k", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },

    { "command": "merge.show", "key": "meta+shift+g", "where": ["browser:mac", "electron:mac"] },
    { "command": "merge.show", "key": "control+shift+g", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },

    { "command": "terminal.shell", "key": "meta+alt+t", "where": ["browser:mac", "electron:mac"] },
    { "command": "terminal.shell", "key": "control+alt+t", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "tree.follow", "key": "control+alt+0", "where": ["browser:win", "browser:linux"] },
    { "command": "tree.follow", "key": "control+0", "where": ["electron:win", "electron:linux"] },
    { "command": "tree.follow", "key": "meta+alt+f", "where": ["browser:mac", "electron:mac"] },
    { "command": "tree.follow", "key": "meta+0", "where": ["browser:mac", "electron:mac"] },
    { "command": "tree.follow", "key": "control+alt+f", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "scripts.packageManager", "key": "meta+shift+p", "where": ["browser:mac", "electron:mac"] },
    { "command": "scripts.packageManager", "key": "control+shift+p", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "search.everywhere", "key": "meta+p", "where": ["browser:mac", "electron:mac"] },
    { "command": "search.everywhere", "key": "control+p", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },

    { "command": "nav.back", "key": "meta+alt+arrowleft", "where": ["electron:mac"] },
    { "command": "nav.back", "key": "control+alt+arrowleft", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "nav.back", "key": "meta+control+arrowleft", "where": ["browser:mac", "electron:mac"] },
    { "command": "nav.forward", "key": "meta+alt+arrowright", "where": ["electron:mac"] },
    { "command": "nav.forward", "key": "control+alt+arrowright", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "nav.forward", "key": "meta+control+arrowright", "where": ["browser:mac", "electron:mac"] },
    { "command": "nav.back", "key": "meta+bracketleft", "where": ["browser:mac", "electron:mac"] },
    { "command": "nav.back", "key": "control+bracketleft", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "nav.forward", "key": "meta+bracketright", "where": ["browser:mac", "electron:mac"] },
    { "command": "nav.forward", "key": "control+bracketright", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },

    { "command": "tree.next", "key": "arrowdown", "when": "tree" },
    { "command": "tree.prev", "key": "arrowup", "when": "tree" },
    { "command": "tree.expand", "key": "arrowright", "when": "tree" },
    { "command": "tree.collapse", "key": "arrowleft", "when": "tree" },
    { "command": "tree.open", "key": "enter", "when": "tree" },
    { "command": "tree.findClear", "key": "escape", "when": "tree" },
    { "command": "tree.rename", "key": "f2", "when": "tree" },
    { "command": "tree.delete", "key": "backspace", "when": "tree" },
    { "command": "tree.newFile", "key": "alt+n", "when": "tree", "where": ["browser:mac"] },
    { "command": "tree.newFile", "key": "control+alt+n", "when": "tree", "where": ["browser:win", "browser:linux"] },
    { "command": "tree.newFile", "key": "meta+n", "when": "tree", "where": ["electron:mac"] },
    { "command": "tree.newFile", "key": "control+n", "when": "tree", "where": ["electron:win", "electron:linux"] },
    { "command": "tree.newFolder", "key": "alt+shift+n", "when": "tree", "where": ["browser:mac"] },
    { "command": "tree.newFolder", "key": "control+alt+shift+n", "when": "tree", "where": ["browser:win", "browser:linux"] },
    { "command": "tree.newFolder", "key": "meta+shift+n", "when": "tree", "where": ["electron:mac"] },
    { "command": "tree.newFolder", "key": "control+shift+n", "when": "tree", "where": ["electron:win", "electron:linux"] },
    { "command": "tree.copy", "key": "meta+c", "when": "tree", "where": ["browser:mac", "electron:mac"] },
    { "command": "tree.copy", "key": "control+c", "when": "tree", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "tree.cut", "key": "meta+x", "when": "tree", "where": ["browser:mac", "electron:mac"] },
    { "command": "tree.cut", "key": "control+x", "when": "tree", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "tree.paste", "key": "meta+v", "when": "tree", "where": ["browser:mac", "electron:mac"] },
    { "command": "tree.paste", "key": "control+v", "when": "tree", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "tree.copyPath", "key": "meta+shift+c", "when": "tree", "where": ["browser:mac", "electron:mac"] },
    { "command": "tree.copyPath", "key": "meta+alt+shift+c", "when": "tree", "where": ["browser:mac", "electron:mac"] },
    { "command": "tree.copyPath", "key": "control+alt+shift+c", "when": "tree", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },

    { "command": "completion.show", "key": "meta+space", "when": "editor", "where": ["browser:mac", "electron:mac"] },
    { "command": "completion.show", "key": "control+space", "when": "editor", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "completion.next", "key": "arrowdown", "when": "completion" },
    { "command": "completion.prev", "key": "arrowup", "when": "completion" },
    { "command": "completion.pageDown", "key": "pagedown", "when": "completion" },
    { "command": "completion.pageUp", "key": "pageup", "when": "completion" },
    { "command": "completion.accept", "key": "enter", "when": "completion" },
    { "command": "completion.replace", "key": "tab", "when": "completion" },
    { "command": "completion.close", "key": "escape", "when": "completion" },
    { "command": "edit.undo", "key": "control+z", "when": "editor", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "edit.undo", "key": "meta+z", "when": "editor", "where": ["browser:mac", "electron:mac"] },
    { "command": "edit.redo", "key": "control+shift+z", "when": "editor", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "edit.redo", "key": "meta+shift+z", "when": "editor", "where": ["browser:mac", "electron:mac"] },
    { "command": "edit.deleteLine", "key": "meta+y", "when": "editor", "where": ["browser:mac", "electron:mac"] },
    { "command": "edit.deleteLine", "key": "control+y", "when": "editor", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "edit.duplicateLine", "key": "meta+d", "when": "editor", "where": ["browser:mac", "electron:mac"] },
    { "command": "edit.duplicateLine", "key": "control+d", "when": "editor", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "edit.toggleComment", "key": "meta+slash", "when": "editor", "where": ["browser:mac", "electron:mac"] },
    { "command": "edit.toggleComment", "key": "control+slash", "when": "editor", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "edit.indent", "key": "tab", "when": "editor" },
    { "command": "edit.unindent", "key": "shift+tab", "when": "editor" },
    { "command": "symbol.goto", "key": "control+b", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "symbol.goto", "key": "meta+b", "where": ["browser:mac", "electron:mac"] },
    { "command": "edit.wordLeft", "key": "alt+arrowleft", "when": "editor", "where": ["browser:mac", "electron:mac"] },
    { "command": "edit.wordLeft", "key": "control+arrowleft", "when": "editor", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "edit.wordLeft", "key": "meta+arrowleft", "when": "editor", "where": ["browser:mac", "electron:mac"] },
    { "command": "edit.wordRight", "key": "alt+arrowright", "when": "editor", "where": ["browser:mac", "electron:mac"] },
    { "command": "edit.wordRight", "key": "control+arrowright", "when": "editor", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "edit.wordRight", "key": "meta+arrowright", "when": "editor", "where": ["browser:mac", "electron:mac"] },
    { "command": "edit.selectWordLeft", "key": "alt+shift+arrowleft", "when": "editor", "where": ["browser:mac", "electron:mac"] },
    { "command": "edit.selectWordLeft", "key": "control+shift+arrowleft", "when": "editor", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "edit.selectWordLeft", "key": "meta+shift+arrowleft", "when": "editor", "where": ["browser:mac", "electron:mac"] },
    { "command": "edit.selectWordRight", "key": "alt+shift+arrowright", "when": "editor", "where": ["browser:mac", "electron:mac"] },
    { "command": "edit.selectWordRight", "key": "control+shift+arrowright", "when": "editor", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "edit.selectWordRight", "key": "meta+shift+arrowright", "when": "editor", "where": ["browser:mac", "electron:mac"] },
    { "command": "edit.moveLineUp", "key": "alt+shift+arrowup", "when": "editor", "where": ["browser:mac", "electron:mac"] },
    { "command": "edit.moveLineUp", "key": "control+shift+arrowup", "when": "editor", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "edit.moveLineDown", "key": "alt+shift+arrowdown", "when": "editor", "where": ["browser:mac", "electron:mac"] },
    { "command": "edit.moveLineDown", "key": "control+shift+arrowdown", "when": "editor", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "edit.addCursorAbove", "key": "alt+arrowup", "when": "editor", "where": ["browser:mac", "electron:mac"] },
    { "command": "edit.addCursorAbove", "key": "control+arrowup", "when": "editor", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] },
    { "command": "edit.addCursorBelow", "key": "alt+arrowdown", "when": "editor", "where": ["browser:mac", "electron:mac"] },
    { "command": "edit.addCursorBelow", "key": "control+arrowdown", "when": "editor", "where": ["browser:win", "browser:linux", "electron:win", "electron:linux"] }
  ]
};

export const KEYMAP_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  properties: {
    version: { type: 'number' },
    bindings: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['key'],
        properties: {
          command: { type: 'string' },
          key: { type: 'string' },
          when: { type: 'string' },
          where: { type: 'array', items: { type: 'string' } },
          remove: { const: true },
        },
      },
    },
  },
} as const;
